import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/requests';

export default function Home({ results }) {
  return (
    <div className="">
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results}/>
      <Footer />
    </div>
  );
};

// Server Side Render
// Loads first
export async function getServerSideProps(context) {
  const genre = context.query.genre; // gets the genre from the url query params.

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then(res => res.json());

  return {
    props: {
      results: request.results
    }
  }
}